In [130]:
import MDAnalysis as mda
import prolif as plf
from rdkit import Chem
import os
from collections import defaultdict
import pandas as pd
import sys
import json
import numpy as np

In [49]:
# Import all pickled IFP dictionaries from prolif_fps directory

IFP_pickles = [file for file in os.listdir('./prolif_fps') if file.endswith('.pkl')]

IFP_dicts = {}

for pickle in IFP_pickles:
    temp_dict = pd.read_pickle(f"./prolif_fps/{pickle}")
    key = list(temp_dict.keys())[0]
    IFP_dicts[key] = temp_dict[key]


# Clean up column levels

for run_key, run_dict in IFP_dicts.items():
    for conformer_key, conformer_dict in IFP_dicts[run_key].items():
        for ligand_key, ligand_list in IFP_dicts[run_key][conformer_key].items():
            # remove superfluous ligand columns level 
            ligand_list[1].columns = ligand_list[1].columns.droplevel("ligand")
            # merge protein and interaction column level
            ligand_list[1].columns = ligand_list[1].columns.map("_".join)

In [76]:
IFP_dicts['12Jun_g543']['4h2i_c_1_dimer_sdf']['4h2i_c_1_dimer_true_actives.sdf'][1].head()

,ILE343.A_Hydrophobic,ILE343.A_VdWContact,VAL344.A_Hydrophobic,VAL344.A_VdWContact,ASN362.A_Hydrophobic,ASN362.A_VdWContact,LEU363.A_Hydrophobic,LEU363.A_VdWContact,ASP366.A_Hydrophobic,ASP366.A_VdWContact,...,TYR539.B_PiStacking,TYR539.B_VdWContact,PRO540.B_VdWContact,ALA541.B_VdWContact,GLU543.B_Hydrophobic,GLU543.B_VdWContact,ARG545.B_Hydrophobic,ARG545.B_Anionic,ARG545.B_PiCation,ARG545.B_VdWContact
Frame,,,,,,,,,,,,,,,,,,,,,
0,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,True,True,True,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,True,True,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
4,False,False,False,False,False,False,False,True,True,False,...,False,False,False,False,False,False,False,False,False,False

In [135]:
IFP_frequencies = {}

for run_key, run_dict in IFP_dicts.items():
    IFP_frequencies[run_key] = {}

    for conformer_key, conformer_dict in IFP_dicts[run_key].items():

        ligand_keys = list(conformer_dict.keys())
        actives_key = [key for key in ligand_keys if key.endswith("true_actives.sdf")][0]
        inactives_key = [key for key in ligand_keys if key.endswith("true_inactives.sdf")][0]
        decoys_key = [key for key in ligand_keys if key.endswith("decoys.sdf")][0]

        actives = IFP_dicts[run_key][conformer_key][actives_key][1]
        freq_actives = actives.mean(axis=0)
        freq_actives.name = 'freq_actives'

        inactives = IFP_dicts[run_key][conformer_key][inactives_key][1]
        freq_inactives = inactives.mean(axis=0)
        freq_inactives.name = 'freq_inactives'

        decoys = IFP_dicts[run_key][conformer_key][decoys_key][1]
        freq_decoys = decoys.mean(axis=0)
        freq_decoys.name = 'freq_decoys'

        new_df = pd.concat(
            [
                freq_actives.rename("freq_actives"),
                freq_inactives.rename("freq_inactives"),
                freq_decoys.rename("freq_decoys"),

            ],
            axis = 1
        )

        new_df['ER_actives_decoys'] = new_df['freq_actives'] / new_df['freq_decoys']
        new_df['Log2_ER_actives_decoys'] = np.log2(new_df['ER_actives_decoys'])

        new_df['ER_actives_inactives'] = new_df['freq_actives'] / new_df['freq_inactives']
        new_df['Log2_ER_actives_inactives'] = np.log2(new_df['ER_actives_inactives'])
        
        IFP_frequencies[run_key][conformer_key] = new_df

In [120]:
IFP_frequencies.keys()

dict_keys(['5Jun_dimer', '12Jun_rg', '12Jun_g543', '16Jun_rg3', '16Jun_rg2'])

In [136]:
IFP_frequencies['12Jun_rg']['4h2i_c_4_dimer_sdf']

,freq_actives,freq_inactives,freq_decoys,ER_actives_decoys,Log2_ER_actives_decoys,ER_actives_inactives,Log2_ER_actives_inactives
LEU363.A_VdWContact,0.070175,0.059524,0.161109,0.435578,-1.198997,1.178947,0.237499
ASP366.A_Hydrophobic,0.192982,0.250000,0.372447,0.518148,-0.948565,0.771930,-0.373458
ASP366.A_VdWContact,0.333333,0.583333,0.711755,0.468326,-1.094415,0.571429,-0.807355
ILE369.A_Hydrophobic,0.245614,0.202381,0.190079,1.292167,0.369792,1.213622,0.279319
ILE369.A_VdWContact,0.438596,0.452381,0.493122,0.889428,-0.169051,0.969529,-0.044644
...,...,...,...,...,...,...,...
ARG545.B_Anionic,NaN,NaN,0.007712,NaN,NaN,NaN,NaN
ARG545.B_PiCation,NaN,NaN,0.008962,NaN,NaN,NaN,NaN
LYS547.B_Hydrophobic,NaN,NaN,0.005836,NaN,NaN,NaN,NaN
LYS547.B_Anionic,NaN,NaN,0.043977,NaN,NaN,NaN,NaN
LYS547.B_PiCation,NaN,NaN,0.004585,NaN,NaN,NaN,NaN

In [137]:
df = IFP_frequencies['12Jun_rg']['4h2i_c_4_dimer_sdf'].dropna()

In [138]:
df.sort_values(by='freq_actives', ascending=False)

,freq_actives,freq_inactives,freq_decoys,ER_actives_decoys,Log2_ER_actives_decoys,ER_actives_inactives,Log2_ER_actives_inactives
GLU543.B_VdWContact,0.982456,0.928571,0.871822,1.126900,0.172360,1.058030,0.081380
GLU543.A_VdWContact,0.982456,0.940476,0.895790,1.096748,0.133233,1.044637,0.063002
GLU543.A_Hydrophobic,0.947368,0.785714,0.547937,1.728974,0.789917,1.205742,0.269921
GLU543.B_Hydrophobic,0.947368,0.928571,0.696332,1.360513,0.444151,1.020243,0.028913
HIS456.B_VdWContact,0.736842,0.571429,0.445602,1.653587,0.725599,1.289474,0.366782
TYR484.A_VdWContact,0.684211,0.809524,0.682368,1.002701,0.003891,0.845201,-0.242633
TYR539.B_VdWContact,0.649123,0.642857,0.713839,0.909341,-0.137107,1.009747,0.013993
HIS456.A_VdWContact,0.649123,0.666667,0.550438,1.179285,0.237912,0.973684,-0.038474
TYR484.A_Hydrophobic,0.596491,0.666667,0.358691,1.662966,0.733759,0.894737,-0.160465
TYR539.B_Hydrophobic,0.561404,0.630952,0.602126,0.932369,-0.101027,0.889772,-0.168493
LEU475.A_VdWContact,0.543860,0.309524,0.510838,1.064642,0.090369,1.757085,0.813184
HIS456.B_PiStacking,0.491228,0.202381,0.069195,7.099133,2.827643,2.427245,1.279319
ILE369.A_VdWContact,0.438596,0.452381,0.493122,0.889428,-0.169051,0.969529,-0.044644
TYR484.B_VdWContact,0.438596,0.285714,0.262609,1.670148,0.739976,1.535088,0.618321
SER385.A_VdWContact,0.403509,0.178571,0.294081,1.372101,0.456387,2.259649,1.176099
GLY454.A_VdWContact,0.368421,0.535714,0.429762,0.857267,-0.222184,0.687719,-0.540108
ARG545.A_Hydrophobic,0.368421,0.309524,0.111505,3.304083,1.724250,1.190283,0.251305
ALA541.B_VdWContact,0.350877,0.130952,0.438516,0.800147,-0.321663,2.679426,1.421924
ASP366.A_VdWContact,0.333333,0.583333,0.711755,0.468326,-1.094415,0.571429,-0.807355
HIS456.A_PiStacking,0.315789,0.154762,0.053356,5.918586,2.565252,2.040486,1.028913
LYS547.B_VdWContact,0.280702,0.119048,0.169862,1.652524,0.724671,2.357895,1.237499
LYS547.A_VdWContact,0.263158,0.285714,0.160692,1.637654,0.711631,0.921053,-0.118644
ARG545.A_VdWContact,0.263158,0.464286,0.541684,0.485814,-1.041523,0.566802,-0.819084
ILE369.A_Hydrophobic,0.245614,0.202381,0.190079,1.292167,0.369792,1.213622,0.279319
GLY544.B_VdWContact,0.245614,0.190476,0.153814,1.596824,0.675205,1.289474,0.366782
GLY544.A_VdWContact,0.245614,0.321429,0.234890,1.045658,0.064411,0.764133,-0.388105
TYR484.B_Hydrophobic,0.210526,0.083333,0.097332,2.162966,1.113011,2.526316,1.337035
ASP366.A_Hydrophobic,0.192982,0.250000,0.372447,0.518148,-0.948565,0.771930,-0.373458
PRO540.B_VdWContact,0.175439,0.238095,0.407253,0.430785,-1.214959,0.736842,-0.440573
TYR484.A_PiStacking,0.157895,0.083333,0.053147,2.970898,1.570899,1.894737,0.921997
TYR539.A_Hydrophobic,0.157895,0.071429,0.125677,1.256350,0.329238,2.210526,1.144390
LEU475.A_Hydrophobic,0.140351,0.035714,0.101084,1.388461,0.473486,3.929825,1.974465
TYR539.B_PiStacking,0.140351,0.095238,0.121926,1.151117,0.203035,1.473684,0.559427
PRO540.A_VdWContact,0.140351,0.166667,0.315340,0.445078,-1.167869,0.842105,-0.247928
TYR539.A_VdWContact,0.140351,0.059524,0.244060,0.575067,-0.798198,2.357895,1.237499
MET535.B_Hydrophobic,0.122807,0.071429,0.107545,1.141915,0.191455,1.719298,0.781820
HIS383.A_VdWContact,0.122807,0.023810,0.052730,2.328965,1.219689,5.157895,2.366782
ALA541.A_VdWContact,0.087719,0.095238,0.219883,0.398936,-1.325772,0.921053,-0.118644
LEU363.A_VdWContact,0.070175,0.059524,0.161109,0.435578,-1.198997,1.178947,0.237499
TYR531.A_VdWContact,0.070175,0.071429,0.355982,0.197132,-2.342765,0.982456,-0.025535
TYR484.B_PiStacking,0.052632,0.023810,0.005419,9.712551,3.279850,2.210526,1.144390
ARG545.A_PiCation,0.052632,0.071429,0.075240,0.699519,-0.515565,0.736842,-0.440573
PRO482.A_VdWContact,0.052632,0.023810,0.037099,1.418687,0.504556,2.210526,1.144390
MET535.B_VdWContact,0.052632,0.083333,0.099208,0.530517,-0.914528,0.631579,-0.662965
ASP366.B_VdWContact,0.035088,0.047619,0.215298,0.162973,-2.617297,0.736842,-0.440573
HIS456.A_PiCation,0.017544,0.023810,0.017090,1.026530,0.037775,0.736842,-0.440573
MET535.A_VdWContact,0.017544,0.011905,0.090038,0.194851,-2.359560,1.473684,0.559427
TYR531.A_Hydrophobic,0.017544,0.023810,0.075865,0.231251,-2.112467,0.736842,-0.440573
GLY453.A_VdWContact,0.017544,0.083333,0.073781,0.237784,-2.072278,0.210526,-2.247928
GLU543.A_Cationic,0.017544,0.023810,0.149229,0.117563,-3.088488,0.736842,-0.440573
LEU475.B_VdWContact,0.017544,0.035714,0.050438,0.347832,-1.523536,0.491228,-1.025535
HIS456.B_PiCation,0.017544,0.023810,0.009170,1.913078,0.935896,0.736842,-0.440573
TYR531.B_VdWContact,0.017544,0.023810,0.149229,0.117563,-3.088488,0.736842,-0.440573
TYR531.B_Hydrophobic,0.017544,0.035714,0.031055,0.564936,-0.823841,0.491228,-1.025535